Repository GDGCosenza/hacktoberfest2019, pull requests merged in 2019-10, with the labels that each got.

#2 Useless commit
  README.md
  res/images/logo.png
Labels: bug

#5 hello in swift
  hello.swift
Labels: good first issue

#6 Ciao a tutti!
  Hacktoberfest.java
Labels: help wanted

#9 hello in python
  hello.py
Labels: enhancement
